name: Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: unbutu-latest

  deploy:
    runs-on: unbutu-latest
    strategy:
      matrix:
        node-version: [20]
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm nx run-many -t build
